// common
export const GOTO_MAIN_PAGE = 'GOTO_MAIN_PAGE';
export const GOTO_SUB_PAGE = 'GOTO_SUB_PAGE';

// real-time query
export const ADD_QUERY_HISTORY_ITEM = 'ADD_QUERY_HISTORY_ITEM';
export const DELETE_QUERY_HISTORY_ITEM = 'DELETE_QUERY_HISTORY_ITEM';
export const CLEAR_QUERY_HISTORY_LIST = 'CLEAR_QUERY_HISTORY_LIST';
export const UPDATE_QUERY_RESULT = 'UPDATE_QUERY_RESULT';
export const CLEAR_QUERY_RESULT = 'CLEAR_QUERY_RESULT';
export const SELECT_BUS_LINE = 'SELECT_BUS_LINE';